version: '3.4'

services:
  discoverscript1:
    image: discoverscript1
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 app/datascraper.py "]
    ports:
      - 5678:5678
